dist:
  name: span-report-collector
  description: custom OpenTelemetry Collector to export hourly, daily, and monthly statistics of spans
  output_path: ./dist

exporters:
  - gomod: github.com/kmuto/span-report-collector/spanreportexporter v0.0.7
    path: ./spanreportexporter
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.142.0
