receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  reportexporter:
    path: "./span_report.txt"
    verbose: true
    report_interval: 1m

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [reportexporter]
