receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  spanreportexporter:
    path: "./span_report.txt"
    report_interval: 1h
    tui: false
    verbose: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [spanreportexporter]
